version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Build started on date
      - sam package
        --template-file template.yml
        --s3-bucket put-event-bucket
        --output-template-file packaged-template.yml

artifacts:
  files:
    template.yml